pdf_regex: '^td2 - (.+)\.pdf$'
html_regex: '^td2 - (.+)\.html$'
files_path: '~/pdf-ocr/td2'
book_path: '~/pdf-ocr/td2.pdf'

shift_modifier: '14'

book:
  name_prefix: 'Часть вторая'
  tree_prefix: 'II.'
  name: 'Антропогенезис'
  name_comment: '(эволюция человечества)'
  synopsis: |
            Представлено издание второе, репринтное, 2006 г.
            Год первого издания: 1994 г.
            640 страниц. Формат 70х100 1/16. Твердая обложка, тиснение
  chapters:
    -
      name: 'СТАНЦЫ ИЗ КНИГИ ДЗИАН'
      parts:
      pages: '2-19'
    -
      name_prefix: 'Беседа первая'
      name: 'Эволюция: аспекты и образы'
      parts:
        -
          name: 'Части Беспредельности и Вечности — четыре Цикла, четыре Юги, четыре возраста, четыре цифры.'
          name_comment: 'Некоторое уточнение к первой Беседе из первой книги.'
          pages: '20-20'
        -
          name: 'Жизнь — это царство материи.'
          pages: '34-43'
        -
          name: 'Эволюция или эманация?'
          pages: '44-52'
        -
          name: 'Чтобы Высшее стало более высоким, оно должно стать... нижайшим.'
          pages: '53-53'
        -
          name: 'Какая у эволюции... форма? Или о змее, которая кусает свой хвост.'
          pages: '54-66'
      pages: '20-33'
    -
      name_prefix: 'Беседа вторая'
      name: 'Храм Бога Живого: о человеке внутреннем и внешнем'
      parts:
        -
          name: 'Отрицать или допустить? Что разумнее?'
          pages: '77-82'
        -
          name: 'Взглянув в зеркало, скажи: "Это — не я. Это моя одежда".'
          pages: '83-89'
        -
          name: 'Древо Жизни Вечной.'
          name_comment: 'Или о человеке внутреннем, называемом Индивидуальностью.'
          pages: '90-97'
        -
          name: 'Созданный из праха.'
          name_comment: 'Или о человеке внешнем, называемом личностью.'
          pages: '98-104'
        -
          name: 'Не распинай Христа!'
          pages: '105-117'
        -
          name: 'Мяч ударяется о землю.'
          name_comment: 'Некоторое расширение понятия смысла воплощений на Земле и забытый стих из юношеской тетради.'
          pages: '118-121'
        -
          name: 'Некоторые акценты, расставленные в схеме семи человеческих принципов-тел.'
          pages: '122-138'
      pages: '67-76'
    -
      name_prefix: 'Беседа третья'
      name: 'Предки Лунные и Солнечные'
      parts:
        -
          name: 'Великие Восставшие.'
          name_comment: 'Или в чем тайна "проклятия" Ангелов, которые отказались творить по приказу Бога.'
          pages: '146-156'
        -
          name: 'Вначале были Лунные Предки.'
          pages: '157-158'
        -
          name: 'От камня — до человека: луняне заселяют Землю.'
          pages: '159-168'
        -
          name: 'Физическая природа сама по себе не может создать человека разумного.'
          pages: '169-176'
      pages: '139-145'
    -
      name_prefix: 'Беседа четвертая'
      name: 'Расы Человеческие и Материки. Расы Первая и Вторая'
      parts:
        -
          name: 'Подобное знает лишь подобное себе.'
          pages: '178-182'
        -
          name: 'Семь Рас с центром посредине.'
          pages: '183-186'
        -
          name: 'Существо, над которым не властно время.'
          pages: '187-189'
        -
          name: 'На этой Земле первым был человек.'
          pages: '190-193'
        -
          name: 'Семь Адамов и Семь Ев в Семи Раях.'
          pages: '194-196'
        -
          name: 'Семь Материков.'
          name_comment: 'Или Семь райских садов для Адамов и Ев.'
          pages: '197-200'
        -
          name: 'Бог создает "твердь посреди вод".'
          pages: '201-202'
        -
          name: 'Первая Раса: "тени" "Теней".'
          name_comment: 'Или люди астральные.'
          pages: '203-211'
        -
          name: 'Вторая Раса. Или потомство, которое съело Отцов.'
          pages: '212-218'
        -
          name: 'Где же логика?'
          pages: '219-223'
      pages: '177-177'
    -
      name_prefix: 'Беседа пятая'
      name: 'Раса Третья — Лемурия'
      parts:
        -
          name: 'Земля, которой больше нет.'
          pages: '225-226'
        -
          name: 'Они до сих пор видят "звезду светлую и утреннюю".'
          pages: '227-232'
        -
          name: 'Гибель Лемурии.'
          pages: '233-236'
        -
          name: 'Что за люди: запоминать не могли ничего, а знали все.'
          pages: '237-244'
        -
          name: 'Эта самая таинственная Третья Раса.'
          pages: '245-252'
        -
          name: 'Человек разумный, человек физический.'
          pages: '253-258'
        -
          name: 'О Первом грехопадении.'
          name_comment: 'Или о том, что случилось в Раю.'
          pages: '259-268'
        -
          name: 'Был ли Бог у Лемурийцев?'
          pages: '269-275'
      pages: '224-224'
    -
      name_prefix: 'Беседа шестая'
      name: 'Четвертая Раса: Атланты — большинство человечества'
      parts:
        -
          name: 'Миф — это не сказка, но история.'
          pages: '282-289'
        -
          name: '25 тысяч книг и статей и одна, но Великая Книга.'
          pages: '290-295'
        -
          name: 'Великая Цивилизация.'
          pages: '296-312'
        -
          name: '"Четвертая раса развила речь".'
          name_comment: 'Или о том, что Слово было в... Середине.'
          pages: '313-316'
        -
          name: 'Атлант — отец обезьяны.'
          name_comment: 'Или о втором грехопадении.'
          pages: '317-318'
        -
          name: '"Час пробил. Черная ночь готова".'
          pages: '319-323'
        -
          name: 'А птицы возвращаются домой.'
          pages: '324-328'
      pages: '276-281'
    -
      name_prefix: 'Беседа седьмая'
      name: 'Сатана Бога'
      parts:
        -
          name: 'Эволюция — это устремление к совершенному.'
          pages: '331-335'
        -
          name: 'Если есть "северный" полюс и "южный", то должно быть и нечто третье, называемое их синтезом.'
          name_comment: 'О единстве противоположностей.'
          pages: '336-349'
        -
          name: 'Как дьявол оказался в Раю?'
          pages: '350-354'
        -
          name: 'О "Медном Змие" Моисея.'
          name_comment: 'Или превращение Бога в Сатану.'
          pages: '355-364'
        -
          name: 'Того ли проклинаем, христиане?'
          name_comment: 'Или откуда у Сатаны рога? Или о Люцифере — звезде "сатанинской".'
          pages: '365-375'
        -
          name: '"Обезьяна" Христа.'
          name_comment: 'Или фальшивый двойник-перевертыш.'
          pages: '376-386'
        -
          name: 'Падший Ангел — князь мира сего.'
          pages: '387-400'
        -
          name: 'Поднимаясь помни о возможности падения.'
          name_comment: 'Расширение представления о причине падения Люцифера.'
          pages: '401-411'
        -
          name: 'Говорит Великий Учитель.'
          name_comment: 'Несколько строк из книги "Надземное" ("Братство", II часть).'
          pages: '412-414'
        -
          name: 'Матерь Мира лик Свой сокрыла.'
          pages: '415-419'
        -
          name: 'Законы Ману.'
          pages: '420-422'
        -
          name: 'Сошествие Христа в ад и приговор Сатане.'
          pages: '423-432'
        -
          name: '"Борьба с силами Света наполняет его отчаянием"'
          name_comment: 'из писем Е. И. Рерих.'
          pages: '433-439'
      pages: '329-330'
    -
      name_prefix: 'Беседа восьмая'
      name: 'Мы — дети своего Вайвасвата Ману или Раса Пятая — Арийская.'
      parts:
        -
          name: 'Белокожие, светловолосые, светлоглазые?'
          pages: '446-451'
        -
          name: 'Молодость человечества или длинная дорога ума к сердцу.'
          pages: '452-461'
        -
          name: 'Мы — акселераты, искусственно созданные.'
          pages: '462-467'
        -
          name: 'Генеалогическое древо Пятой Коренной Расы.'
          pages: '468-472'
        -
          name: 'О Циклах — в который раз.'
          pages: '473-475'
        -
          name: 'Вайвасвата — наш спаситель.'
          pages: '476-487'
        -
          name: 'Ману-антара: Предок один, но Предков... два.'
          pages: '488-493'
        -
          name: '"Я не дерзаю открыть это вполне..."'
          name_comment: 'отрывок из письма старшего Махатмы (1882 г.).'
          pages: '494-502'
      pages: '440-445'
    -
      name_prefix: 'Беседа девятая'
      name: 'Слепая вера? Или вера на знании?'
      parts:
        -
          name: 'Книга Золотых Правил.'
          pages: '504-512'
        -
          name: 'Хлеб из вчерашних зерен: Библия — основа христианской веры.'
          pages: '513-528'
        -
          name: 'И в большом и в малом... позаимствовали.'
          pages: '529-543'
        -
          name: 'Кришна, Готама Будда. Иисус Христос — Единое Триязычное Пламя Вечности.'
          pages: '544-566'
        -
          name: 'Тайна Никейского Собора.'
          pages: '567-568'
        -
          name: 'И это — тоже христианство.'
          name_comment: 'Дополнение к Беседе седьмой и для сравнения — с первой главой Беседы восьмой.'
          pages: '569-586'
        -
          name: 'Моление о Чаше.'
          name_comment: 'Размышление в свете Тайной Доктрины о молении Иисуса Христа в ночи Святого Четверга накануне казни.'
          pages: '587-599'
        -
          name: '"Чаша Христа".'
          name_comment: 'Философско-поэтическая расшифровка одноименной картины Н. К. Рериха.'
          pages: '600-610'
        -
          name: '"Нет религии выше истины" — девиз, принятый Всемирным Теософским Обществом.'
          pages: '611-615'
        -
          name: 'Рамакришна — живой храм всех религий.'
          pages: '616-619'
        -
          name: 'Знамя Мира — Знамя Культуры.'
          name_comment: 'Три малых красных круга и большом Круге на белом полотнище. Отрывки из произведений Н. К. Рериха, президента Всемирной Лиги Культуры.'
          pages: '620-625'
      pages: '503-503'

  parts:

  pages: '~13-1'

pages_dictionary:
  -
    page: '-13'
    url_name: 'I'
  -
    page: '-12'
    url_name: 'II'
  -
    page: '-11'
    url_name: 'III'
  -
    page: '-10'
    url_name: 'IV'
  -
    page: '-9'
    url_name: 'V'
  -
    page: '-8'
    url_name: 'VI'
  -
    page: '-7'
    url_name: 'VII'
  -
    page: '-6'
    url_name: 'VIII'
  -
    page: '-5'
    url_name: 'IX'
  -
    page: '-4'
    url_name: 'X'
  -
    page: '-3'
    url_name: 'XI'
  -
    page: '-2'
    url_name: 'XII'
  -
    page: '-1'
    url_name: 'XIII'
  -
    page: '0'
    url_name: 'XIV'
  -
    page: '24'
    name: 'Как мы растем? Или движение по семи ступенькам.'
  -
    page: '31'
    name: 'Дыхание Космоса или о Четырехтактном Двигателе Вечного Движения.'
  -
    page: '34'
    name: 'Хочешь стать человеком? Стань вначале Богом!'
  -
    page: '56'
    name: '"Танцуем все! Два шага вперед и шаг... назад!". Или о том, можно.ли подниматься... опускаясь?'
  -
    page: '58'
    name: 'Когда закончилась Эманация, для нас все только началось. Или место встречи миров изменить нельзя.'
  -
    page: '67'
    name: 'Три точки зрения современной науки и одна точка зрения Науки Древней'
  -
    page: '73'
    name: 'Быть может ВСЕ!'
  -
    page: '77'
    name: 'Несколько параграфов из некоторых книг серии "Живая Этика" или Агни Йога.'
  -
    page: '124'
    name: 'Атма — частица Вселенского Духа (дух духовного тела).'
  -
    page: '125'
    name: 'Манас высший (Буддхи-Манас) (разум духовного тела).'
  -
    page: '128'
    name: 'Антахкарана — тропа между внутренним и внешним человеком (золотой мост для человека в белых одеждах).'
  -
    page: '129'
    name: 'Манас низший (Кама-манас) (низший, физический ум, интеллект, ум желаний, рассудок, животная душа, высшее тонкое тело или ментальное тело).'
  -
    page: '132'
    name: 'Астральное тело — Линга Шарира (тело страстей и желаний, низшее тонкое тело).'
  -
    page: '136'
    name: 'Прана — это Дыхание, это Жизнь (жизненное тело, принцип, нераздельный от всех проявлений в космосе).'
  -
    page: '139'
    name: '"О мое сердце, сердце Предка, не рассоединись со мною...".'
  -
    page: '151'
    name: 'Год сотворения Человека Разумного или когда же Боги стали человеками?'
  -
    page: '152'
    name: 'Четыре Элемента Четвертого Круга Земли. Что символизирует Огонь?'
  -
    page: '155'
    name: 'Йога Огня — синтез всех Йог. Несколько строк из книги "Агни Йога" (из одноименной серии).'
  -
    page: '169'
    name: 'Несколько слов о Сознании.'
  -
    page: '171'
    name: 'Низшее не может сотворить высшее.'
  -
    page: '203'
    name: 'Человек без... формы.'
  -
    page: '206'
    name: 'Астральные двойники.'
  -
    page: '209'
    name: 'Существа, не знавшие смерти.'
  -
    page: '212'
    name: 'Родитель внутри... дитяти?'
  -
    page: '213'
    name: 'Человек-невидимка бродит без одежд.'
  -
    page: '215'
    name: '"Капли пота", которые затвердели.'
  -
    page: '245'
    name: 'Человек в виде... "капли пота" и...'
  -
    page: '246'
    name: '...рожденный из Яйца.'
  -
    page: '248'
    name: 'Великая Андрогина.'
  -
    page: '250'
    name: 'Легенда об Андрогинах.'
  -
    page: '253'
    name: 'Бхарата-Варша — колыбель человечества, состоящего из мужчин и женщин.'
  -
    page: '255'
    name: '"Теперь мы будем творить".'
  -
    page: '265'
    name: '"... чтобы не случилось худшего".'
  -
    page: '268'
    name: 'Природой было предназаначено другое?'
  -
    page: '269'
    name: 'Они Их видели каждый день.'
  -
    page: '271'
    name: '"Сыны Бога" и "Священный Остров". Несколько фрагментов из Антропогенезиса.'
  -
    page: '273'
    name: 'Из Письма Махатмы от 9.VII.1882 г.'
  -
    page: '276'
    name: 'Кто сказал древним грекам о знойном севере?'
  -
    page: '291'
    name: 'Платон знал Тайную Доктрину: его "9000 лет были правильным числом".'
  -
    page: '296'
    name: 'Когда погибла Атлантида?'
  -
    page: '300'
    name: 'Какими вы были? Несколько разрозненных кусочков гигантского панно под названием "Атлантида".'
  -
    page: '329'
    name: 'Во Вселенной зла нет, есть несовершенство.'
  -
    page: '336'
    name: 'Страдающий "человек, который смеется".'
  -
    page: '341'
    name: '"Demon est Deus inversus".'
  -
    page: '344'
    name: 'He ищи Дьявола во Вселенной.'
  -
    page: '355'
    name: 'Маска, кто ты? Еще один аспект змеиного символа.'
  -
    page: '358'
    name: '..."И шестикрылый Серафим на перепутье мне явился" или об Огненных Змиях.'
  -
    page: '387'
    name: '"Падение Ангелов" — всемирная аллегория.'
  -
    page: '390'
    name: '"Месяц под косой блестит, а во лбу — звезда горит" или снова о рогатом Сатане со звездою меж рогов.'
  -
    page: '396'
    name: 'Дьявол растворился в своем человечестве не сразу.'
  -
    page: '399'
    name: 'И в восхищении своем не преступи Закон.'
  -
    page: '405'
    name: 'Князь Мира сего, но не... Князь Вселенной.'
  -
    page: '409'
    name: 'Заложники Дьявола.'
  -
    page: '415'
    name: 'Что было главным в планах Сатаны, начавшим битву с Богом.'
  -
    page: '440'
    name: 'Европа начиналась в... Азии.'
  -
    page: '484'
    name: '"Я сказал: вы — боги; и сыны Всевышнего — все вы..." или о том, что все человечество — едино.'
  -
    page: '485'
    name: 'Боги становятся людьми.'
  -
    page: '513'
    name: 'Богом данная книга.'
  -
    page: '516'
    name: 'Закрытая шкатулка древних мастеров... без ключа.'
  -
    page: '544'
    name: 'Несколько параллелей из "Разоблаченной Изиды".'
  -
    page: '555'
    name: 'Три Спасителя с... одной биографией?'
  -
    page: '557'
    name: 'Легенды о трех Спасителях.'
  -
    page: '560'
    name: 'Кришна — Христос.'
  -
    page: '562'
    name: 'Будда — Христос.'
