pdf_regex: '^td3 - (.+)\.pdf$'
html_regex: '^td3 - (.+)\.html$'
files_path: '~/pdf-ocr/td3'
book_path: '~/pdf-ocr/td3.pdf'

shift_modifier: '12'

book:
  name_prefix: 'Часть третья'
  tree_prefix: 'III.'
  name: 'Великие облики Учителей и понятие об Агни Йоге'
  name_comment: ''
  synopsis: |
            Представлено издание второе, репринтное, 2006 г.
            Год первого издания: 1994 г.
            656 страниц. Формат 70х100 1/16. Твердая обложка, тиснение
  sections:
    -
      name_prefix: 'Раздел I'
      name: 'Великие Облики Учителей'
      name_comment: 'Махатмы — Ученики Махатм. Философско-поэтические трактовки к картинам Н. К. Рериха в свете "Тайной Доктрины" и Агни Йоги и очерки о главных героях эзотерических полотен.'
      parts:
        -
          name: 'Вместо предисловия."Молния. Зов неба".'
          name_comment: '(Трактовка к картине).'
          pages: '3-4'
        -
          name: 'Одинокий Страж у фонтана Предвечной Мудрости.'
          name_comment: '(Отрывок из "Тайной Доктрины").'
          pages: '5-9'
        -
          name: 'Елена Рерих. Великие Воплощенные.'
          name_comment: '(Фрагменты из писем 1935—1937 гг.)'
          pages: '10-16'
      pages: '1-2'
      chapters:
        -
          name: 'Эзотерическая живопись Н. К. Рериха'
          name_comment: 'Биографический штрих к Именам Великих Воплощенных. Понятие Единства в многообразии Вечной Истины, излучаемой из Единого Источника. Ритмы интуиции в поэтических намеках.'
          parts:
            -
              name: 'Введение.'
              pages: '19-24'
            -
              name: 'Кришна.'
              pages: '25-42'
            -
              name: 'Арджуна.'
              pages: '43-56'
            -
              name: 'Будда Готама (Готама Сиддхарта Шакьямуни).'
              pages: '57-92'
            -
              name: 'Иисус Христос.'
              pages: '93-132'
            -
              name: 'Моисей (Моше).'
              pages: '133-152'
            -
              name: 'Мухаммад (Мухаммед, Магомет).'
              pages: '153-178'
            -
              name: 'Зороастр (Заратуштра, Заратустра).'
              pages: '179-192'
            -
              name: 'Конфуций (Кун Фу-цзы, Кун-цзы).'
              pages: '193-216'
            -
              name: 'Гесер-Хан (Гэсэр, Гессар, Гесэр).'
              pages: '217-228'
            -
              name: 'Сергий Радонежский.'
              pages: '229-246'
            -
              name: 'Иенно Гуйо Дья.'
              pages: '247-256'
            -
              name: 'Николай и Елена Рерих.'
              pages: '257-276'
            -
              name: 'Отрывки из тайных тибетских пророчеств о Шамбале и Майтрейе.'
              pages: '277-289'
            -
              name: 'Штрихи к облику Елены Рерих'
              name_comment: '(Из очерков Николая Рериха, посвященных жене).'
              pages: '290-291'
            -
              name: 'Елена Рерих: несколько провидческих намеков о приблизившемся грозном времени, в которое решается участь человечества Земли'
              name_comment: '(Строки из писем разных лет).'
              pages: '292-296'
            -
              name: 'Урусвати. Контур Великого Облика, появившийся при первом чтении книги "Надземное".'
              pages: '297-310'
            -
              name: 'Шамбала. Несколько фрагментов из книги Н. К. Рериха.'
              pages: '311-318'
            -
              name: 'Вместо заключения.'
              pages: '319-321'
            -
              name: 'Елена Рерих — Президенту США Ф-Д. Рузвельту (10.10.34).'
              pages: '322-323'
            -
              name: 'Владыка Шамбалы — Владыка Трех Миров, которого человечество знает под разными именами, но имени Его не знает, говорит.'
              pages: '324-330'
          pages: '17-18'

    -
      name_prefix: 'Раздел II'
      name: 'Кульминация Тайной Доктрины — Агни Йога Или Огненный Мост в Новую Эпоху'
      name_comment: 'Несколько параграфов из книг серии Агни Йога (Живая Этика) и — вместо предисловия к ним в свете обсуждаемой темы — штрих к портрету советского общества конца 80-х начала 90-х годов ХХ-го века.'
      parts:
        -
          name: '"...Феномен духовный — феномен небывалый".'
          pages: '333-354'
        -
          name: 'Не зная броду...'
          pages: '355-361'
        -
          name: 'Тайная наука — двулика и обоюдоостра.'
          pages: '362-383'
        -
          name: 'В тумане иллюзий можно шагнуть в пропасть.'
          name_comment: 'Об опасности медиумизма и низшего психизма.'
          pages: '384-400'
        -
          name: 'Я летаю в "иные миры" — значит "я избран".'
          pages: '401-410'
        -
          name: '"Я был свидетелем".'
          name_comment: 'В продолжение предыдущей темы.'
          pages: '411-414'
        -
          name: 'Кадуцей — древний символ науки... будущего.'
          pages: '415-417'
        -
          name: 'Конец эпохи предрассудков.'
          pages: '418-443'
        -
          name: 'Понятие о перевоплощении и карме.'
          pages: '444-479'
        -
          name: 'Был ли Маугли человеком разумным.'
          name_comment: 'Или Зачем ребенку взрослые, а ученику — учитель?'
          pages: '480-485'
        -
          name: 'Еще раз произнесем Священные Слова "Учитель" и "Шамбала".'
          pages: '486-490'
        -
          name: 'Живая Этика — Наука о человеке для человека.'
          pages: '491-494'
        -
          name: 'Агни Йога — дорога к Огненному Миру.'
          pages: '495-532'
        -
          name: 'Прежде чем открыть первую страницу Сокровенного Учения.'
          pages: '533-560'
      pages: '331-332'
    -
      name: 'Агни Йога (Живая Этика)'
      name_comment: 'Несколько фрагментов из книг Сокровенного Учения Махатм и "выступление" Владыки Шамбалы на страницах одной из партийных газет в день рождения Той, которая принесла Западу первую светлую Весть о Махатмах'
      parts:
        -
          name: '"Я, Владыка Шамбалы, говорю...".'
          pages: '565-570'
      pages: '561-564'
      chapters:
        -
          name: 'Краткий конспект Агни Йоги.'
          name_comment: 'Строки из текстов книг для первого ознакомления.'
          parts:
            -
              name: '"Листы Сада Мории". Часть первая ("Зов"). 1924 г.'
              pages: '573-575'
            -
              name: '"Листы Сада Мории". Часть вторая ("Озарение"). 1925 г.'
              pages: '576-580'
            -
              name: '"Община" 1926, 1927 гг.'
              pages: '581-586'
            -
              name: '"Агни Йога" 1929 г.'
              pages: '587-591'
            -
              name: '"Беспредельность" (2 части) 1930 г.'
              pages: '592-595'
            -
              name: '"Иерархия" 1931 г.'
              pages: '596-600'
            -
              name: '"Сердце" 1932 г.'
              pages: '601-605'
            -
              name: '"Мир Огненный" (3 части) 1933, 1934, 1935 гг.'
              pages: '606-612'
            -
              name: '"АУМ" 1936 г.'
              pages: '613-618'
            -
              name: '"Братство". Часть первая. 1937 г.'
              pages: '619-627'
          pages: '571-572'
        -
          name: 'Елена Петровна Блаватская'
          parts:
            -
              name: 'Вместо послесловия. Елена Блаватская: с чего надо начинать?'
              pages: '629-637'
            -
              name: 'Пояснения к тексту.'
              pages: '638-644'
          pages: '628-628'

  parts:

  pages: '~11-0'

pages_dictionary:
  -
    page: '-11'
    url_name: 'I'
  -
    page: '-10'
    url_name: 'II'
  -
    page: '-9'
    url_name: 'III'
  -
    page: '-8'
    url_name: 'IV'
  -
    page: '-7'
    url_name: 'V'
  -
    page: '-6'
    url_name: 'VI'
  -
    page: '-5'
    url_name: 'VII'
  -
    page: '-4'
    url_name: 'VIII'
  -
    page: '-3'
    url_name: 'IX'
  -
    page: '-2'
    url_name: 'X'
  -
    page: '-1'
    url_name: 'XI'
  -
    page: '0'
    url_name: 'XII'
  -
    page: '39'
    name: '"Кришна".'
  -
    page: '41'
    name: '"Весна в Кулу. Кришна".'
  -
    page: '53'
    name: '"Арджуна".'
  -
    page: '85'
    name: 'Строки из текстов Агни Йоги — "Община".'
  -
    page: '89'
    name: '"Бхагаван".'
  -
    page: '120'
    name: 'Елена Рерих — об Иисусе Христе.'
    name_comment: '(Несколько фрагментов из II-го тома Писем 1936—1937 гг.).'
  -
    page: '124'
    name: 'Несколько строк из книги "Надземное" о Христе.'
  -
    page: '128'
    name: '"Знаки Христа".'
  -
    page: '130'
    name: '"Сошествие во ад".'
  -
    page: '148'
    name: '"Моисей-водитель".'
  -
    page: '175'
    name: '"Магомет на горе Хира".'
  -
    page: '190'
    name: '"Зороастр".'
  -
    page: '210'
    name: 'Изречения Конфуция.'
  -
    page: '213'
    name: '"Философ. Тишина".'
  -
    page: '226'
    name: '"Гесер-хан".'
  -
    page: '235'
    name: '"Слуга России — родом Он из Огненного Мира...".'
  -
    page: '240'
    name: '"Св. Сергий".'
  -
    page: '243'
    name: 'Елена Рерих — о святом Сергии Радонежском, христианстве и России.'
  -
    page: '255'
    name: '"Иенно Гуйо Дья — друг путников".'
  -
    page: '265'
    name: 'Святослав Рерих. Слово об отце (в сокращении).'
  -
    page: '269'
    name: 'Николай Рерих. Молодое движение.'
  -
    page: '271'
    name: '"Плато Чантанг".'
  -
    page: '274'
    name: '"Канченджанга".'
  -
    page: '275'
    name: '"Чинтамани".'
  -
    page: '302'
    name: '"Ведущая".'
  -
    page: '304'
    name: '"Властитель ночи".'
  -
    page: '306'
    name: '"Камень несущая" ("Держательница Мира").'
  -
    page: '309'
    name: 'Поэтический эскиз к портрету Елены Ивановны Рерих работы С. Н. Рериха.'
  -
    page: '314'
    name: '"Весть Шамбалы".'
  -
    page: '317'
    name: '"Тень Учителя".'
  -
    page: '318'
    name: '"Гуру Камбала".'
  -
    page: '333'
    name: 'Несколько общих фраз о некоторых высших психических способностях Е. П. Блаватской.'
  -
    page: '353'
    name: 'Она ушла, сказав о себе много и не сказав ничего.'
  -
    page: '362'
    name: 'Берегите свои души!'
  -
    page: '373'
    name: 'Сатана правит бал.'
    name_comment: '(Отрывок из письма великого оккультиста и ясновидца XVI века М. Нострадамуса и три газетные рекламы четыре века спустя).'
  -
    page: '382'
    name: 'Елена Блаватская. Благотворно ли применение концентраций?'
    name_comment: '(Отрывок из статьи, помещенной в III томе "Тайной Доктрины").'
  -
    page: '444'
    name: 'Переселение Душ: блеф или загадка?'
    name_comment: '(Заметка из журнала).'
  -
    page: '447'
    name: 'О перевоплощении.'
  -
    page: '462'
    name: 'Мысли великих людей о перевоплощении.'
  -
    page: '469'
    name: 'О Карме.'
  -
    page: '495'
    name: '"Огненная пора началась".'
  -
    page: '516'
    name: 'Змий над "чашей" Огня.'
  -
    page: '533'
    name: 'Некоторые необходимые указания и советы для начинающих.'
  -
    page: '556'
    name: 'Несколько обобщающих советов, закрепляющих уже сказанное, и некоторые новые разъяснения и предупреждения ученикам, данные Е. И. Рерих.'
  -
    page: '629'
    name: 'Заметки Роберта Боуэна, кавалера ордена 2-й степени, сделанные им в 1891 г. за 19 дней до смерти Е. П. Блаватской.'
